apiVersion: v1
kind: Service
metadata:
  name: mcp-trino
  namespace: dataplatform
  labels:
    app: mcp-trino
spec:
  type: ClusterIP
  selector:
    app: mcp-trino
  ports:
    - name: http
      port: 3010
      targetPort: http
